# Generated by Django 5.0.2 on 2024-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasMedicasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaCita',
            field=models.DateField(),
        ),
    ]
